name: CI
on:
  - push
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform fmt -check
      - run: terraform init -lock-timeout=5m
        env:
          TF_IN_AUTOMATION: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_tailscale_api_key: ${{ secrets.TAILSCALE_API_KEY }}
          TF_VAR_tailscale_tailnet: ${{ secrets.TAILSCALE_TAILNET }}
      - run: terraform validate -no-color
        env:
          TF_IN_AUTOMATION: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_tailscale_api_key: ${{ secrets.TAILSCALE_API_KEY }}
          TF_VAR_tailscale_tailnet: ${{ secrets.TAILSCALE_TAILNET }}
      - run: terraform plan -no-color -input=false -lock-timeout=5m
        env:
          TF_IN_AUTOMATION: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          TF_VAR_tailscale_api_key: ${{ secrets.TAILSCALE_API_KEY }}
          TF_VAR_tailscale_tailnet: ${{ secrets.TAILSCALE_TAILNET }}
